name: CI_pipeline

on: 
  push:
   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_code
        uses: actions/checkout@v4
      - name:  build
        uses: gadopyatikna/go-sample-action@v4
